### ISSUE TITLE
How to download the datasets?

### ISSUE THREAD

**Issue by xingshuohan** [cv-core/MIT-Driverless-CV-TrainingInfra#16]
Seems like we cannot access the link.

**Comment by FedeAi** [comment]
Does someone have a backup of the dataset?

**Comment by bartoszptak** [comment]
Bump. I also need it.

**Comment by bartoszptak** [comment]
Hi, I found it.
Here are links:
* images: `aHR0cHM6Ly9jaG11cmEucHV0LnBvem5hbi5wbC9zL1puVWNlUWd2M0lWWXczWQ==`
* train labels: `aHR0cHM6Ly9jaG11cmEucHV0LnBvem5hbi5wbC9zL1F6MmRuWUI1eUlRcEoxWg==`
* val labels: `aHR0cHM6Ly9jaG11cmEucHV0LnBvem5hbi5wbC9zL09xVWZ4R1dSeEhENVVCZA==`

You need to use base64 to text converter.

**Comment by Fleming-Sung** [comment]
> Hi, I found it. Here are links:
> 
> * images: `aHR0cHM6Ly9jaG11cmEucHV0LnBvem5hbi5wbC9zL1puVWNlUWd2M0lWWXczWQ==`
> * train labels: `aHR0cHM6Ly9jaG11cmEucHV0LnBvem5hbi5wbC9zL1F6MmRuWUI1eUlRcEoxWg==`
> * val labels: `aHR0cHM6Ly9jaG11cmEucHV0LnBvem5hbi5wbC9zL09xVWZ4R1dSeEhENVVCZA==`
> 
> You need to use base64 to text converter.

Hi bartoszptak,

Could you please tell me, how can I use these links?
Are they for any particular app or website?

Thank you very much!

**Comment by bartoszptak** [comment]
@Fleming-Sung sure! 
Go to [https://www.base64decode.org/](https://www.base64decode.org/), for example. Copy hashes from above to new lines each. Next, select the option "decode each line separately", press the decode button, and copy links to a web browser.

**Comment by Fleming-Sung** [comment]
> * aHR0cHM6Ly9jaG11cmEucHV0LnBvem5hbi5wbC9zL1puVWNlUWd2M0lWWXczWQ==

Got it!!!
And it is downloading now! This is really very helpful.
Thanks again!

**Comment by JustSomeRandomUsername** [comment]
Do you have links to the RektNet dataset? Those seem to be dead too.

**Comment by Fleming-Sung** [comment]
> Do you have links to the RektNet dataset? Those seem to be dead too.

Hi, for my very experience, the original link can only be fetched though the gsutil in terminal. While, you can not download any dataset through the browser.

**Comment by Fleming-Sung** [comment]
> Do you have links to the RektNet dataset? Those seem to be dead too.

Hi, for my very experience, the original link can only be fetched though the gsutil in terminal. While, you can not download any dataset through the browser.
If you are not available with gsutil, you can download the datasets from my cloud-disk, which contains all the dataset of this repo. 
Below is the link:
Link：https://pan.baidu.com/s/1rAIXQfhRo7mY9kTLMHNwZQ 
Passward：o5xt

**Comment by space192** [comment]
hey @Fleming-Sung would it be possible for you to upload it somewhere else ? I'm outside of China and cannot create a baidu account to download the dataset :/

**Comment by Sibozhu** [comment]
here's the dataset download link on google drive: https://drive.google.com/file/d/13a6J2I-xoz4kvEpv2yk8IlFgFdYaxgZ3/view?usp=sharing
