### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by EugenKarasev** [cv-core/MIT-Driverless-CV-TrainingInfra#2]
Hi!
Could you, please, provide dataset format for targets?
Thank's

![Dataset](https://user-images.githubusercontent.com/50025549/70377960-d2413b80-192b-11ea-8208-f242abebe91e.png)

**Comment by Sibozhu** [comment]
Hey @EugenKarasev, thanks for your interest. 

Can you elaborate on what's the "target" you are referring to here? 

Cones' labels in each picture is formatted as (X,Y,H,W)

**Comment by EugenKarasev** [comment]
> Hey @EugenKarasev, thanks for your interest.
> 
> Can you elaborate on what's the "target" you are referring to here?
> 
> Cone's label in each picture is formatted as (X,Y,H,W)

Hello
Sorry for the inaccurate question.
I meant where are Yellow and where are Blue cones in this table.

**Comment by Sibozhu** [comment]
Sorry @EugenKarasev we don't have a reasonable amount of good quality YOLO label for blue and yellow cones at this moment. We might release them in the future.
