### ISSUE TITLE
Unable to download RektNet dataset

### ISSUE THREAD

**Issue by h-anton** [cv-core/MIT-Driverless-CV-TrainingInfra#36]
Hello,

I would like to download the RektNet dataset, but I am unable to.
When I try to do `wget https://storage.googleapis.com/mit-driverless-open-source/RektNet_Dataset.zip
`, as described in the Jupyter Notebook tutorial, I am getting the following output:
```
--2023-11-17 17:17:26--  https://storage.googleapis.com/mit-driverless-open-source/RektNet_Dataset.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.36.59, 142.250.179.155, 142.250.179.219, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.36.59|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-11-17 17:17:26 ERROR 403: Forbidden.
```
How can I access the dataset?

Kind regards,

Anton

**Comment by space192** [comment]
did you ever find a way to download the dataset ?

**Comment by Sibozhu** [comment]
here's the dataset download link on google drive: https://drive.google.com/file/d/13a6J2I-xoz4kvEpv2yk8IlFgFdYaxgZ3/view?usp=sharing

**Comment by Gabrocecco** [comment]
Hi sorry for bothering, I was trying to download the dataset too, but Google Drive link seems to be not active.
