### ISSUE TITLE
Perspective-n-point.

### ISSUE THREAD

**Issue by EugenKarasev** [cv-core/MIT-Driverless-CV-TrainingInfra#4]
Hello.
Could you tell me, how you, having found 7 points on the cone and knowing the parameters of the calibrated camera and the dimensions of the cone, determine the position of the cone relative to the camera?
If you can, please show me the implementation in the code, or tell me what helped you in solving this problem.
Thanks.

**Comment by Sibozhu** [comment]
Hello @EugenKarasev, thanks for your interest in our work.

> how you found 7 points on the cone

We developed a dedicated neural network to detect the 7 keypoints on the cone: https://github.com/cv-core/MIT-Driverless-CV-TrainingInfra/tree/master/RektNet

> How did we know the parameters of the calibrated camera? 

We calibrated the camera in our own, manually.

> How we know dimensions of the cone?

The shape of the cone is accessible through FSG's official competition manual, plus you can also measure it by yourself.

> Implementation in the code

Pytorch Training: https://github.com/cv-core/MIT-Driverless-CV-TrainingInfra/tree/master/RektNet

TensorRT inference: https://github.com/cv-core/tensorrt_ros/blob/master/KeypointDetector.cpp

**Comment by EugenKarasev** [comment]
Yes, thank you.
But I am interested in exactly, how you determine the position of the cone?

**Comment by shikhar413** [comment]
Hi @EugenKarasev, this repo has all of the source files related to object detection. What you'd be looking for is a PnP solver for which there are multiple open-source implementations. You could try OpenCV's `solvePnP` or `solvePnPRansac` functions, alternatively [this repo](https://github.com/midjji/pnp) solves PnP using a lambda twist P3P solver which is supposed to be faster and more stable
