### ISSUE TITLE
Label format - height is scaled with img width?

### ISSUE THREAD

**Issue by David-Un-ger** [cv-core/MIT-Driverless-CV-TrainingInfra#6]
I have downloaded your dataset and the labels in the YOLO format (1 label file per image).

I tried to visualize the bounding boxes by using the labels and rescaling the bboxes by the image width and heigth to get the absolute pixel values.

Is it possible that you mixed up the scaling when you created the label files?

With the following code, I get the correct label position: 

```
        h, w = img.shape[0], img.shape[1]

        for line in f.readlines():
            l = line.split()
            x_min = int(float(l[1])*w)
            y_min = int(float(l[2])*h)
            box_height = int(float(l[3])*w)
            box_width = int(float(l[4])*h)
```

At least from my understanding, the box_height should be scaled with the image height to get the absolute pixel values:
```
        h, w = img.shape[0], img.shape[1]

        for line in f.readlines():
            l = line.split()
            x_min = int(float(l[1])*w)
            y_min = int(float(l[2])*h)
            box_height = int(float(l[3])*h)
            box_width = int(float(l[4])*w)

```

**Comment by Sibozhu** [comment]
Hi @FinnHendricks Thanks for your interest on our project. If I understand your question correctly, you are asking if we forgot to also scale the label size regarding image scale?

I think it happened here:
https://github.com/cv-core/MIT-Driverless-CV-TrainingInfra/blob/bb8d6e22d8211aad1cd56f698723db8812bd6623/CVC-YOLOv3/utils/datasets.py#L180

Let me know if there are any following questions
