### ISSUE TITLE
Labelled cone dataset.

### ISSUE THREAD

**Issue by pratham-gupta** [cv-core/MIT-Driverless-CV-TrainingInfra#7]
The all.csv file only have bounding box for images but not the class attribute for blue and yellow cone. Can you provide csv file with class labels as well. It would save lot of my time. thanks in advance.

**Comment by ChristianMilianti** [comment]
Hi cv-core team, would it be possible to be provided with the csv file with the class labels as mentioned above, it would be highly appreciated. Thank you for your contribution and hard work.

**Comment by Sibozhu** [comment]
[all.csv](https://github.com/cv-core/MIT-Driverless-CV-TrainingInfra/files/6388089/all.csv)

Hi @Negsii and @pratham-gupta , thanks for your support. Here's the colored label for our dataset. The label format is in: 
[X, Y, H, W, color]

Sibo

**Comment by pratham-gupta** [comment]
Thank You. Really appreciate that. You guys did an amazing job.

**Comment by ChristianMilianti** [comment]
Thank you so much for your prompt reply @Sibozhu , we really appreciate that! Once again, well done on this fantastic job.
